-- 1. Creación e inicialización del entorno
#	CREATE DATABASE IF NOT EXISTS enigh_db;
USE enigh_db;
DROP TABLE IF EXISTS concentradohogar;
DROP TABLE IF EXISTS poblacion;

-- Estructura y carga para la tabla: concentradohogar
DROP TABLE IF EXISTS `concentradohogar`;

CREATE TABLE IF NOT EXISTS `concentradohogar` (
    `folioviv` BIGINT,
    `foliohog` BIGINT,
    `ubica_geo` BIGINT,
    `tam_loc` BIGINT,
    `est_socio` BIGINT,
    `est_dis` BIGINT,
    `upm` BIGINT,
    `factor` BIGINT,
    `clase_hog` BIGINT,
    `sexo_jefe` BIGINT,
    `edad_jefe` BIGINT,
    `educa_jefe` BIGINT,
    `tot_integ` BIGINT,
    `hombres` BIGINT,
    `mujeres` BIGINT,
    `mayores` BIGINT,
    `menores` BIGINT,
    `p12_64` BIGINT,
    `p65mas` BIGINT,
    `ocupados` BIGINT,
    `percep_ing` BIGINT,
    `perc_ocupa` BIGINT,
    `ing_cor` DOUBLE,
    `ingtrab` DOUBLE,
    `trabajo` DOUBLE,
    `sueldos` DOUBLE,
    `horas_extr` DOUBLE,
    `comisiones` DOUBLE,
    `aguinaldo` DOUBLE,
    `indemtrab` DOUBLE,
    `otra_rem` DOUBLE,
    `remu_espec` DOUBLE,
    `negocio` DOUBLE,
    `noagrop` DOUBLE,
    `industria` DOUBLE,
    `comercio` DOUBLE,
    `servicios` DOUBLE,
    `agrope` DOUBLE,
    `agricolas` DOUBLE,
    `pecuarios` DOUBLE,
    `reproducc` DOUBLE,
    `pesca` DOUBLE,
    `otros_trab` DOUBLE,
    `rentas` DOUBLE,
    `utilidad` DOUBLE,
    `arrenda` DOUBLE,
    `transfer` DOUBLE,
    `jubilacion` DOUBLE,
    `becas` DOUBLE,
    `donativos` DOUBLE,
    `remesas` DOUBLE,
    `bene_gob` DOUBLE,
    `transf_hog` DOUBLE,
    `trans_inst` DOUBLE,
    `estim_alqu` DOUBLE,
    `otros_ing` DOUBLE,
    `gasto_mon` DOUBLE,
    `alimentos` DOUBLE,
    `ali_dentro` DOUBLE,
    `cereales` DOUBLE,
    `carnes` DOUBLE,
    `pescado` DOUBLE,
    `leche` DOUBLE,
    `huevo` DOUBLE,
    `aceites` DOUBLE,
    `tuberculo` DOUBLE,
    `verduras` DOUBLE,
    `frutas` DOUBLE,
    `azucar` DOUBLE,
    `cafe` DOUBLE,
    `especias` DOUBLE,
    `otros_alim` DOUBLE,
    `bebidas` DOUBLE,
    `ali_fuera` DOUBLE,
    `tabaco` DOUBLE,
    `vesti_calz` DOUBLE,
    `vestido` DOUBLE,
    `calzado` DOUBLE,
    `vivienda` DOUBLE,
    `alquiler` DOUBLE,
    `pred_cons` DOUBLE,
    `agua` DOUBLE,
    `energia` DOUBLE,
    `limpieza` DOUBLE,
    `cuidados` DOUBLE,
    `utensilios` DOUBLE,
    `enseres` DOUBLE,
    `salud` DOUBLE,
    `ambul_serv` DOUBLE,
    `aten_hosp` DOUBLE,
    `medic_prod` DOUBLE,
    `transporte` DOUBLE,
    `publico` DOUBLE,
    `foraneo` DOUBLE,
    `adqui_vehi` DOUBLE,
    `mantenim` DOUBLE,
    `refaccion` DOUBLE,
    `combus` DOUBLE,
    `comunica` DOUBLE,
    `educa_espa` DOUBLE,
    `educacion` DOUBLE,
    `esparci` DOUBLE,
    `paq_turist` DOUBLE,
    `personales` DOUBLE,
    `cuida_pers` DOUBLE,
    `acces_pers` DOUBLE,
    `otros_gas` DOUBLE,
    `transf_gas` DOUBLE,
    `percep_tot` DOUBLE,
    `retiro_inv` DOUBLE,
    `prestamos` DOUBLE,
    `otras_perc` DOUBLE,
    `ero_nm_viv` DOUBLE,
    `ero_nm_hog` DOUBLE,
    `erogac_tot` DOUBLE,
    `cuota_viv` DOUBLE,
    `mater_serv` DOUBLE,
    `material` DOUBLE,
    `servicio` DOUBLE,
    `deposito` DOUBLE,
    `prest_terc` DOUBLE,
    `pago_tarje` DOUBLE,
    `deudas` DOUBLE,
    `balance` DOUBLE,
    `otras_erog` DOUBLE,
    `smg` DOUBLE
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/concentradohogar_clean.csv' 
INTO TABLE `concentradohogar` 
FIELDS TERMINATED BY ','  
ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;


-- Estructura y carga para la tabla: poblacion


DROP TABLE IF EXISTS `poblacion`;

CREATE TABLE IF NOT EXISTS `poblacion` (
    `folioviv` BIGINT,
    `foliohog` BIGINT,
    `numren` BIGINT,
    `parentesco` BIGINT,
    `sexo` BIGINT,
    `edad` BIGINT,
    `madre_hog` BIGINT,
    `madre_id` VARCHAR(255),
    `padre_hog` BIGINT,
    `padre_id` VARCHAR(255),
    `pais_nac` BIGINT,
    `afrod` BIGINT,
    `disc_ver` VARCHAR(255),
    `disc_oir` VARCHAR(255),
    `disc_brazo` VARCHAR(255),
    `disc_camin` VARCHAR(255),
    `disc_apren` VARCHAR(255),
    `disc_vest` VARCHAR(255),
    `disc_habla` VARCHAR(255),
    `disc_acti` VARCHAR(255),
    `edu_ini` VARCHAR(255),
    `no_asis` VARCHAR(255),
    `hablaind` VARCHAR(255),
    `lenguaind` VARCHAR(255),
    `hablaesp` VARCHAR(255),
    `comprenind` VARCHAR(255),
    `etnia` VARCHAR(255),
    `alfabetism` VARCHAR(255),
    `asis_esc` VARCHAR(255),
    `no_asisb` VARCHAR(255),
    `nivel` VARCHAR(255),
    `grado` VARCHAR(255),
    `tipoesc` VARCHAR(255),
    `tiene_b` VARCHAR(255),
    `otorg_b` VARCHAR(255),
    `forma_b` VARCHAR(255),
    `tiene_c` VARCHAR(255),
    `otorg_c` VARCHAR(255),
    `forma_c` VARCHAR(255),
    `nivelaprob` VARCHAR(255),
    `gradoaprob` VARCHAR(255),
    `antec_esc` VARCHAR(255),
    `residencia` VARCHAR(255),
    `edo_conyug` VARCHAR(255),
    `pareja_hog` VARCHAR(255),
    `conyuge_id` VARCHAR(255),
    `segsoc` VARCHAR(255),
    `ss_aa` VARCHAR(255),
    `ss_mm` VARCHAR(255),
    `redsoc_1` VARCHAR(255),
    `redsoc_2` VARCHAR(255),
    `redsoc_3` VARCHAR(255),
    `redsoc_4` VARCHAR(255),
    `redsoc_5` VARCHAR(255),
    `redsoc_6` VARCHAR(255),
    `hor_1` VARCHAR(255),
    `min_1` VARCHAR(255),
    `usotiempo1` VARCHAR(255),
    `hor_2` VARCHAR(255),
    `min_2` VARCHAR(255),
    `usotiempo2` VARCHAR(255),
    `hor_3` VARCHAR(255),
    `min_3` VARCHAR(255),
    `usotiempo3` VARCHAR(255),
    `hor_4` VARCHAR(255),
    `min_4` VARCHAR(255),
    `usotiempo4` VARCHAR(255),
    `hor_5` VARCHAR(255),
    `min_5` VARCHAR(255),
    `usotiempo5` VARCHAR(255),
    `hor_6` VARCHAR(255),
    `min_6` VARCHAR(255),
    `usotiempo6` VARCHAR(255),
    `hor_7` VARCHAR(255),
    `min_7` VARCHAR(255),
    `usotiempo7` VARCHAR(255),
    `hor_8` VARCHAR(255),
    `min_8` VARCHAR(255),
    `usotiempo8` VARCHAR(255),
    `inst_1` VARCHAR(255),
    `inst_2` VARCHAR(255),
    `inst_3` VARCHAR(255),
    `inst_4` VARCHAR(255),
    `inst_5` VARCHAR(255),
    `inst_6` VARCHAR(255),
    `inst_7` VARCHAR(255),
    `inst_8` VARCHAR(255),
    `inst_9` VARCHAR(255),
    `atemed` VARCHAR(255),
    `inscr_1` VARCHAR(255),
    `inscr_2` VARCHAR(255),
    `inscr_3` VARCHAR(255),
    `inscr_4` VARCHAR(255),
    `inscr_5` VARCHAR(255),
    `inscr_6` VARCHAR(255),
    `inscr_7` VARCHAR(255),
    `inscr_8` VARCHAR(255),
    `prob_anio` VARCHAR(255),
    `prob_mes` VARCHAR(255),
    `prob_sal` VARCHAR(255),
    `aten_sal` VARCHAR(255),
    `servmed_1` VARCHAR(255),
    `servmed_2` VARCHAR(255),
    `servmed_3` VARCHAR(255),
    `servmed_4` VARCHAR(255),
    `servmed_5` VARCHAR(255),
    `servmed_6` VARCHAR(255),
    `servmed_7` VARCHAR(255),
    `servmed_8` VARCHAR(255),
    `servmed_9` VARCHAR(255),
    `servmed_10` VARCHAR(255),
    `servmed_11` VARCHAR(255),
    `hh_lug` VARCHAR(255),
    `mm_lug` VARCHAR(255),
    `hh_esp` VARCHAR(255),
    `mm_esp` VARCHAR(255),
    `pagoaten_1` VARCHAR(255),
    `pagoaten_2` VARCHAR(255),
    `pagoaten_3` VARCHAR(255),
    `pagoaten_4` VARCHAR(255),
    `pagoaten_5` VARCHAR(255),
    `pagoaten_6` VARCHAR(255),
    `pagoaten_7` VARCHAR(255),
    `noatenc_1` VARCHAR(255),
    `noatenc_2` VARCHAR(255),
    `noatenc_3` VARCHAR(255),
    `noatenc_4` VARCHAR(255),
    `noatenc_5` VARCHAR(255),
    `noatenc_6` VARCHAR(255),
    `noatenc_7` VARCHAR(255),
    `noatenc_8` VARCHAR(255),
    `noatenc_9` VARCHAR(255),
    `noatenc_10` VARCHAR(255),
    `noatenc_11` VARCHAR(255),
    `noatenc_12` VARCHAR(255),
    `noatenc_13` VARCHAR(255),
    `noatenc_14` VARCHAR(255),
    `noatenc_15` VARCHAR(255),
    `noatenc_16` VARCHAR(255),
    `norecib_1` VARCHAR(255),
    `norecib_2` VARCHAR(255),
    `norecib_3` VARCHAR(255),
    `norecib_4` VARCHAR(255),
    `norecib_5` VARCHAR(255),
    `norecib_6` VARCHAR(255),
    `norecib_7` VARCHAR(255),
    `norecib_8` VARCHAR(255),
    `norecib_9` VARCHAR(255),
    `norecib_10` VARCHAR(255),
    `norecib_11` VARCHAR(255),
    `razon_1` VARCHAR(255),
    `razon_2` VARCHAR(255),
    `razon_3` VARCHAR(255),
    `razon_4` VARCHAR(255),
    `razon_5` VARCHAR(255),
    `razon_6` VARCHAR(255),
    `razon_7` VARCHAR(255),
    `razon_8` VARCHAR(255),
    `razon_9` VARCHAR(255),
    `razon_10` VARCHAR(255),
    `razon_11` VARCHAR(255),
    `diabetes` VARCHAR(255),
    `pres_alta` VARCHAR(255),
    `peso` VARCHAR(255),
    `segvol_1` VARCHAR(255),
    `segvol_2` VARCHAR(255),
    `segvol_3` VARCHAR(255),
    `segvol_4` VARCHAR(255),
    `segvol_5` VARCHAR(255),
    `segvol_6` VARCHAR(255),
    `segvol_7` VARCHAR(255),
    `hijos_viv` VARCHAR(255),
    `hijos_mue` VARCHAR(255),
    `hijos_sob` VARCHAR(255),
    `trabajo_mp` VARCHAR(255),
    `motivo_aus` VARCHAR(255),
    `act_pnea1` VARCHAR(255),
    `act_pnea2` VARCHAR(255),
    `num_trabaj` VARCHAR(255),
    `c_futuro` VARCHAR(255),
    `ct_futuro` VARCHAR(255),
    `entidad` BIGINT,
    `est_dis` BIGINT,
    `upm` BIGINT,
    `factor` BIGINT
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/poblacion_clean.csv'
INTO TABLE `poblacion`
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS `poblacion`;

CREATE TABLE IF NOT EXISTS `poblacion` (
    `folioviv` BIGINT,
    `foliohog` BIGINT,
    `numren` BIGINT,
    `parentesco` BIGINT,
    `sexo` BIGINT,
    `edad` BIGINT,
    `madre_hog` BIGINT,
    `madre_id` TEXT,
    `padre_hog` BIGINT,
    `padre_id` TEXT,
    `pais_nac` BIGINT,
    `afrod` BIGINT,
    `disc_ver` TEXT,
    `disc_oir` TEXT,
    `disc_brazo` TEXT,
    `disc_camin` TEXT,
    `disc_apren` TEXT,
    `disc_vest` TEXT,
    `disc_habla` TEXT,
    `disc_acti` TEXT,
    `edu_ini` TEXT,
    `no_asis` TEXT,
    `hablaind` TEXT,
    `lenguaind` TEXT,
    `hablaesp` TEXT,
    `comprenind` TEXT,
    `etnia` TEXT,
    `alfabetism` TEXT,
    `asis_esc` TEXT,
    `no_asisb` TEXT,
    `nivel` TEXT,
    `grado` TEXT,
    `tipoesc` TEXT,
    `tiene_b` TEXT,
    `otorg_b` TEXT,
    `forma_b` TEXT,
    `tiene_c` TEXT,
    `otorg_c` TEXT,
    `forma_c` TEXT,
    `nivelaprob` TEXT,
    `gradoaprob` TEXT,
    `antec_esc` TEXT,
    `residencia` TEXT,
    `edo_conyug` TEXT,
    `pareja_hog` TEXT,
    `conyuge_id` TEXT,
    `segsoc` TEXT,
    `ss_aa` TEXT,
    `ss_mm` TEXT,
    `redsoc_1` TEXT,
    `redsoc_2` TEXT,
    `redsoc_3` TEXT,
    `redsoc_4` TEXT,
    `redsoc_5` TEXT,
    `redsoc_6` TEXT,
    `hor_1` TEXT,
    `min_1` TEXT,
    `usotiempo1` TEXT,
    `hor_2` TEXT,
    `min_2` TEXT,
    `usotiempo2` TEXT,
    `hor_3` TEXT,
    `min_3` TEXT,
    `usotiempo3` TEXT,
    `hor_4` TEXT,
    `min_4` TEXT,
    `usotiempo4` TEXT,
    `hor_5` TEXT,
    `min_5` TEXT,
    `usotiempo5` TEXT,
    `hor_6` TEXT,
    `min_6` TEXT,
    `usotiempo6` TEXT,
    `hor_7` TEXT,
    `min_7` TEXT,
    `usotiempo7` TEXT,
    `hor_8` TEXT,
    `min_8` TEXT,
    `usotiempo8` TEXT,
    `inst_1` TEXT,
    `inst_2` TEXT,
    `inst_3` TEXT,
    `inst_4` TEXT,
    `inst_5` TEXT,
    `inst_6` TEXT,
    `inst_7` TEXT,
    `inst_8` TEXT,
    `inst_9` TEXT,
    `atemed` TEXT,
    `inscr_1` TEXT,
    `inscr_2` TEXT,
    `inscr_3` TEXT,
    `inscr_4` TEXT,
    `inscr_5` TEXT,
    `inscr_6` TEXT,
    `inscr_7` TEXT,
    `inscr_8` TEXT,
    `prob_anio` TEXT,
    `prob_mes` TEXT,
    `prob_sal` TEXT,
    `aten_sal` TEXT,
    `servmed_1` TEXT,
    `servmed_2` TEXT,
    `servmed_3` TEXT,
    `servmed_4` TEXT,
    `servmed_5` TEXT,
    `servmed_6` TEXT,
    `servmed_7` TEXT,
    `servmed_8` TEXT,
    `servmed_9` TEXT,
    `servmed_10` TEXT,
    `servmed_11` TEXT,
    `hh_lug` TEXT,
    `mm_lug` TEXT,
    `hh_esp` TEXT,
    `mm_esp` TEXT,
    `pagoaten_1` TEXT,
    `pagoaten_2` TEXT,
    `pagoaten_3` TEXT,
    `pagoaten_4` TEXT,
    `pagoaten_5` TEXT,
    `pagoaten_6` TEXT,
    `pagoaten_7` TEXT,
    `noatenc_1` TEXT,
    `noatenc_2` TEXT,
    `noatenc_3` TEXT,
    `noatenc_4` TEXT,
    `noatenc_5` TEXT,
    `noatenc_6` TEXT,
    `noatenc_7` TEXT,
    `noatenc_8` TEXT,
    `noatenc_9` TEXT,
    `noatenc_10` TEXT,
    `noatenc_11` TEXT,
    `noatenc_12` TEXT,
    `noatenc_13` TEXT,
    `noatenc_14` TEXT,
    `noatenc_15` TEXT,
    `noatenc_16` TEXT,
    `norecib_1` TEXT,
    `norecib_2` TEXT,
    `norecib_3` TEXT,
    `norecib_4` TEXT,
    `norecib_5` TEXT,
    `norecib_6` TEXT,
    `norecib_7` TEXT,
    `norecib_8` TEXT,
    `norecib_9` TEXT,
    `norecib_10` TEXT,
    `norecib_11` TEXT,
    `razon_1` TEXT,
    `razon_2` TEXT,
    `razon_3` TEXT,
    `razon_4` TEXT,
    `razon_5` TEXT,
    `razon_6` TEXT,
    `razon_7` TEXT,
    `razon_8` TEXT,
    `razon_9` TEXT,
    `razon_10` TEXT,
    `razon_11` TEXT,
    `diabetes` TEXT,
    `pres_alta` TEXT,
    `peso` TEXT,
    `segvol_1` TEXT,
    `segvol_2` TEXT,
    `segvol_3` TEXT,
    `segvol_4` TEXT,
    `segvol_5` TEXT,
    `segvol_6` TEXT,
    `segvol_7` TEXT,
    `hijos_viv` TEXT,
    `hijos_mue` TEXT,
    `hijos_sob` TEXT,
    `trabajo_mp` TEXT,
    `motivo_aus` TEXT,
    `act_pnea1` TEXT,
    `act_pnea2` TEXT,
    `num_trabaj` TEXT,
    `c_futuro` TEXT,
    `ct_futuro` TEXT,
    `entidad` BIGINT,
    `est_dis` BIGINT,
    `upm` BIGINT,
    `factor` BIGINT
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/poblacion_clean.csv'
INTO TABLE `poblacion`
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;











